// Code generated by "genSchema --pkg schemas BlockModule"; DO NOT EDIT.

package schemas

// BlockModuleJSONSchema is the JSON schema for the BlockModule struct.
var BlockModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["block"]},
    "modules": {"$ref": "#/definitions/ModulesList"},
    "join": {"type": "string", "description": "Join is a template to use to join together modules.  Defaults to \" \". This will be executed with template data of the form ` + "`" + `{ PrevColors, NextColors, Index }` + "`" + `, where PrevColors is the FG and BG color of last character of the previous module, NextColors is the FG and BG color of the first character of the next module, and Index is the index of the current module in the modules array."}
  },
  "required": ["type", "modules"]}`

