// Code generated by "genSchema --pkg schemas CPUModule"; DO NOT EDIT.

package schemas

// CPUModuleJSONSchema is the JSON schema for the CPUModule struct.
var CPUModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["cpu"]},
    "minPercent": {"type": "number", "description": "MinPercent is the minimum percentage to show the CPU.  Defaults to 5%."}
  },
  "required": ["type"]}`
