// Code generated by "genSchema --pkg schemas CustomModule"; DO NOT EDIT.

package schemas

// CustomModuleJSONSchema is the JSON schema for the CustomModule struct.
var CustomModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["custom"]},
    "command": {"type": "string", "description": "Command is the command to run."},
    "as": {"type": "string", "description": "As will determine how to interpret the result of the command.  One of \"text\", \"json\", \"toml\", or \"yaml\".", "enum": ["text", "json", "toml", "yaml"]},
    "regex": {"type": "string", "description": "Regex is a regular expression used to parse values out of the result of the getter.  If specified, then \"As\" will be ignored."},
    "cache": {"$ref": "#/definitions/CacheSettings"}
  },
  "required": ["type", "command"]}`

