// Code generated by "genSchema --pkg schemas DirectoryModule"; DO NOT EDIT.

package schemas

// DirectoryModuleJSONSchema is the JSON schema for the DirectoryModule struct.
var DirectoryModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "style": {"type": "string", "description": ""},
    "template": {"type": "string", "description": ""},
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["directory"]},
    "homeSymbol": {"type": "string", "description": "HomeSymbol is the symbol to replace the home directory with in directory strings.  Defaults to \"~\"."},
    "readOnlySymbol": {"type": "string", "description": "ReadOnlySymbol is the symbol to append to the directory if it is read-only."},
    "truncateToRepo": {"type": "boolean", "description": "TruncateToRepo controls whether we truncate to the root directory of the git repo or not.  If this is true, and we are in a source code repository, we will replace everything up to the repo root directory with RepoSymbol."},
    "repoSymbol": {"type": "string", "description": "RepoSymbol is a string that will be added as a prefix when we truncate to a repo."},
    "truncationLength": {"type": "integer", "description": "TruncationLength is the maximum number of directories to show. If 0, truncation will be disabled."},
    "truncationSymbol": {"type": "string", "description": "TruncationSymbol will be added to the start of the string in place of any paths that were removed.  Defaults to \"…\"."}
  },
  "additionalProperties": false
}`

