// Code generated by "genSchema --pkg schemas FileModule"; DO NOT EDIT.

package schemas

// FileModuleJSONSchema is the JSON schema for the FileModule struct.
var FileModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["file"]},
    "file": {"type": "string", "description": "From is the file to read data from."},
    "as": {"type": "string", "description": "As will determine how to interpret the contents of the file.  One of \"text\", \"json\", \"toml\", or \"yaml\".", "enum": ["text", "json", "toml", "yaml"]},
    "regex": {"type": "string", "description": "Regex is a regular expression used to parse values out of the result of the getter.  If specified, then \"As\" will be ignored."}
  },
  "required": ["type", "file"]}`

