// Code generated by "genSchema --pkg schemas FlexibleSpaceModule"; DO NOT EDIT.

package schemas

// FlexibleSpaceModuleJSONSchema is the JSON schema for the FlexibleSpaceModule struct.
var FlexibleSpaceModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["flexible_space"]}
  },
  "required": ["type"]}`

