// Code generated by "genSchema --pkg schemas GitHeadModule"; DO NOT EDIT.

package schemas

// GitHeadModuleJSONSchema is the JSON schema for the GitHeadModule struct.
var GitHeadModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["git_head"]},
    "maxTagsToSearch": {"type": "integer", "description": "MaxTagsToSearch is the maximum number of tags to search when checking to see if HEAD is a tagged release.  Defaults to 200."}
  },
  "required": ["type"]}`

