// Code generated by "genSchema --pkg schemas GitModule"; DO NOT EDIT.

package schemas

// GitModuleJSONSchema is the JSON schema for the GitModule struct.
var GitModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["git"]},
    "maxTagsToSearch": {"type": "integer", "description": "MaxTagsToSearch is the maximum number of tags to search when checking to see if HEAD is a tagged release.  Defaults to 200."},
    "rebaseInteractive": {"type": "string", "description": "RebasingInteractive is a description to show when an interactive rebase in in progress."},
    "rebaseMerging": {"type": "string", "description": "RebaseMerging is a description to show when a merge in in progress."},
    "rebasing": {"type": "string", "description": "Rebasing is a description to show when a rebase operation in in progress."},
    "aming": {"type": "string", "description": "AMing is a description to show when an ` + "`" + `am` + "`" + ` operation in in progress."},
    "rebaseAMing": {"type": "string", "description": "RebaseAMing is a description to show when an ambiguous apply-mailbox or rebase is in progress."},
    "merging": {"type": "string", "description": "Merging is a description to show when a merge in in progress."},
    "cherryPicking": {"type": "string", "description": "CherryPicking is a description to show when a cherry-pick in in progress."},
    "reverting": {"type": "string", "description": "Reverting is a description to show when a revert in in progress."},
    "bisecting": {"type": "string", "description": "Bisecting is a description to show when a bisect in in progress."}
  },
  "required": ["type"]}`

