// Code generated by "genSchema --pkg schemas GitDiverged"; DO NOT EDIT.

package schemas

// GitDivergedJSONSchema is the JSON schema for the GitDiverged struct.
var GitDivergedJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["git_diverged"]},
    "aheadSymbol": {"type": "string", "description": "AheadSymbol is the symbol to use when the current branch is ahead of its upstream."},
    "behindSymbol": {"type": "string", "description": "BehindSymbol is the symbol to use when the current branch is behind its upstream."},
    "divergedSymbol": {"type": "string", "description": "DivergedSymbol is the symbol to use when the current branch has diverged from its upstream."},
    "upToDateSymbol": {"type": "string", "description": "UpToDateSymbol is the symbol to use when the current branch is up to date with its upstream."},
    "noUpstreamSymbol": {"type": "string", "description": "NoUpstreamSymbol is the symbol to use when the current branch has no upstream."}
  },
  "required": ["type"]}`

