// Code generated by "genSchema --pkg schemas GitModule"; DO NOT EDIT.

package schemas

// GitModuleJSONSchema is the JSON schema for the GitModule struct.
var GitModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "style": {"type": "string", "description": ""},
    "template": {"type": "string", "description": ""},
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["git"]},
    "aheadStyle": {"type": "string", "description": ""},
    "behindStyle": {"type": "string", "description": ""},
    "aheadBehindStyle": {"type": "string", "description": ""}
  },
  "additionalProperties": false
}`

