// Code generated by "genSchema --pkg schemas GitStateModule"; DO NOT EDIT.

package schemas

// GitStateModuleJSONSchema is the JSON schema for the GitStateModule struct.
var GitStateModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["git_state"]}
  },
  "required": ["type"]}`

