// Code generated by "genSchema --pkg schemas HostnameModule"; DO NOT EDIT.

package schemas

// HostnameModuleJSONSchema is the JSON schema for the HostnameModule struct.
var HostnameModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "style": {"type": "string", "description": ""},
    "template": {"type": "string", "description": ""},
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["hostname"]},
    "showAlways": {"type": "boolean", "description": "ShowAlways will cause the hostname to always be shown.  If false (the default), then the hostname will only be shown if the current session is an SSH session."}
  },
  "additionalProperties": false
}`

