// Code generated by "genSchema --pkg schemas CommonConfig"; DO NOT EDIT.

package schemas

// CommonConfigJSONSchema is the JSON schema for the CommonConfig struct.
var CommonConfigJSONSchema = `{
  "type": "object",
"properties": {
    "style": {"type": "string", "description": "Style is the style to apply to this module."},
    "template": {"type": "string", "description": "Template is a golang template to use to render the output of this module."}
  }}`

