// Code generated by "genSchema --pkg schemas TextModule"; DO NOT EDIT.

package schemas

// TextModuleJSONSchema is the JSON schema for the TextModule struct.
var TextModuleJSONSchema = `{
  "type": "object",
  "properties": {
    "style": {"type": "string", "description": ""},
    "template": {"type": "string", "description": ""},
    "type": {"type": "string", "description": "Type is the type of this module.", "enum": ["text"]},
    "text": {"type": "string", "description": "Text is the text to print."}
  },
  "required": ["text"],
  "additionalProperties": false
}`

