# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - "386"
      - amd64
      - arm64
      - arm
    goarm:
      - "6"
      - "7"
    ldflags:
      - -s -w -X github.com/jwalton/kitsch/cmd.version={{.Version}} -X github.com/jwalton/kitsch/cmd.commit={{.Commit}}
archives:
  - name_template: "kitsch_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
brews:
  - name: kitsch
    goarm: "6"
    tap:
      owner: jwalton
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: goreleaser@lucid.thedreaming.org
    homepage: https://kitschprompt.com
    caveats: |
      Run "kitsch setup" for details about how to configure your shell to use kitsch!
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs'
      - '^test'
      - '^refactor'
      - '^ci'
      - '^build'
  groups:
    - title: Features
      regexp: "^feat[(\\w)]*:+.*$"
      order: 0
    - title: Bug fixes
      regexp: "^fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
