// Code generated by "stringer -type=AsType"; DO NOT EDIT.

package getters

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AsUndefined-0]
	_ = x[AsText-1]
	_ = x[AsJSON-2]
	_ = x[AsYAML-3]
	_ = x[AsTOML-4]
}

const _AsType_name = "AsUndefinedAsTextAsJSONAsYAMLAsTOML"

var _AsType_index = [...]uint8{0, 11, 17, 23, 29, 35}

func (i AsType) String() string {
	if i < 0 || i >= AsType(len(_AsType_index)-1) {
		return "AsType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AsType_name[_AsType_index[i]:_AsType_index[i+1]]
}
