// Code generated by "genSchema --private CacheSettings"; DO NOT EDIT.

package getters

// cacheSettingsJSONSchema is the JSON schema for the CacheSettings struct.
var cacheSettingsJSONSchema = `{
  "type": "object",
  "properties": {
    "enabled": {"type": "boolean", "description": "Enabled is true if caching should be enabled for this getter.  At the moment, this only applied to getters with ` + "`" + `Type: \"custom\"` + "`" + `.  This makes it so we will cache the output of a command instead of re-running that command."}
  },
  "additionalProperties": false
}`

