colors:
  $fg: "#08f"
  $directory: "linear-gradient(#0ff, $fg)"
prompt:
  type: block
  modules:
    - type: time
      style: brightBlack
    - type: block
      style: $directory
      template: "{{ with .Text }}[{{ . }}]{{end}}"
      modules:
        - type: username
        - type: directory
    - type: block
      style: brightYellow
      modules:
        - type: git
        - type: git_status
      template: "{{ with .Text }}[{{ . }}]{{end}}"
    - type: CommandDuration
      style: brightYellow
    - type: prompt
      style: $fg
      errorStyle: brightRed
