colors:
  $foreground: "linear-gradient(#0ff, #08f)"
prompt:
  type: block
  join: " "
  modules:
    - type: time
      style: brightBlack
    - type: directory
      style: $foreground
      template: "[{{.Data.Path}}]"
    - type: block
      style: brightYellow
      modules:
        - type: git
        - type: git_status
      join: " "
      template: "{{ with .Data.Default }}[{{ . }}]{{end}}"
    - type: prompt
      style: brightBlue
      errorStyle: brightRed
