colors:
  $foreground: "linear-gradient(#0ff, #08f)"
prompt:
  type: block
  modules:
    - type: time
      style: brightBlack
    - type: block
      style: $foreground
      template: "{{ with .Text }}[{{ . }}]{{end}}"
      modules:
        - type: username
        - type: directory
    - type: block
      style: brightYellow
      modules:
        - type: git
        - type: git_status
      template: "{{ with .Text }}[{{ . }}]{{end}}"
    - type: prompt
      style: brightBlue
      errorStyle: brightRed
