colors:
  $fg: "#08f"
  $directory: "linear-gradient(#0ff, $fg)"
  $git: brightCyan
  $gitAhead: brightGreen
  $gitBehind: brightRed
  $gitDiverged: brightYellow
prompt:
  type: block
  modules:
    - type: time
      style: brightBlack
    - type: block
      style: $directory
      template: "{{ with .Text }}[{{ . }}]{{end}}"
      modules:
        - type: block
          join: "@"
          modules:
            - type: username
            - type: hostname
        - type: directory
          style: bold
        - type: project
          # template: |
          #   via {{ .Data.ToolSymbol }}@{{ .Data.ToolVersion }}
          #   {{- if .Data.PackageManagerVersion }}/{{ .Data.PackageManagerSymbol }}@{{ .Data.PackageManagerVersion }}{{ end -}}
    - type: block
      style: brightYellow
      modules:
        - type: git
          template: |
            {{- $gitStyles := dict "upToDate" "$git" "ahead" "$gitAhead" "behind" "$gitBehind" "diverged" "$gitDiverged" -}}
            {{- style (get $gitStyles .Data.AheadBehind) .Text -}}
        - type: git_status
      template: "{{ with .Text }}[{{ . }}]{{end}}"
    - type: kubernetes
      style: $fg
    - type: command_duration
      style: brightYellow
    - type: jobs
      style: $fg
    - type: prompt
      style: $fg
      errorStyle: brightRed
